"""
scaffold_prompts.py
===================
Prompt content only. Structure analysis lives in scaffold_analyzer.py, template rendering /
validation / prompt assembly in scaffold_describer.py, model calls and the CLI in
describe_scaffolds.py. To change a prompt, edit this file and nothing else.

Two things live here: the controlled-NL sentence fragments the deterministic draft is built
from, and the system / user / revise / condense prompts used to polish that draft.

Prompt v8 (fixed 2026-07-29)
---------------------------
A description is the INPUT to a SMARTS-generation task. It is read before any structure exists
and more than one structure can satisfy it, so it has to read like the brief a chemist states
when asking for a structure to be made ("a quinazoline core linked through an amide to ..."),
never like a report on a finished object ("this scaffold contains ...").

Five constraints:
  1. A natural, unambiguous sentence comes first.
  2. Say nothing the FACTS do not give. Omitting is fine; adding is not.
  3. The DRAFT is a wording reference only - do not mirror its shape.
  4. Keep the voice uniform across models (the corpus is generated by several of them).
  5. At most four sentences.

Banning nouns does not work: widen the list and the model just moves from "the scaffold" to
"the structure" to "the system" to "the framework". v8 bans the SENTENCE TYPES those nouns
appear in instead - do not open by pointing at the whole thing, do not close with a summary
that restates earlier sentences, and do not pad a sentence with an empty predicate
("forms the core of the scaffold").

The FACTS block changed with it: scaffold_describer.format_facts() used to emit
"- Overall: <aromaticity>; scaffold heteroatoms: <total>." The total invited a whole-scaffold
subject and duplicated the per-ring lines, so it is gone; the aromaticity is kept but phrased
about the rings ("- Aromaticity across the rings: ...") because dropping it measurably lost
that information from the output.

Caveat: the ASCII-only rule under UNIFORM VOICE is not enforceable by prompt alone (gpt-oss
emits non-breaking hyphens regardless). Generated text is therefore normalised downstream by
scaffold_describer.normalize_text().

Rationale, measurements and example sentences: description_results/report_default_vs_v8.html
Pre-v8 prompt, kept for restore only:       prompt_var/default.py
"""
from __future__ import annotations


# --------------------------------------------------------------------------- #
#  Controlled-NL sentence templates filled by the deterministic renderer.
#  scaffold_describer.render_template() turns the analysis dict into a faithful
#  one-to-four-sentence draft, which the LLM then polishes.
# --------------------------------------------------------------------------- #
TEMPLATE_SENTENCES = {
    # One ring system.
    "single_mono": "The scaffold is {a} {core_name} ring.",
    "single_poly": "The scaffold is built on {a} {core_name}, {topology_desc}.",
    # Multiple ring systems (core plus connections).
    "multi": "The scaffold contains {a} {core_name} core {connections}.",
    # Heteroatom pattern.
    "hetero_one": "The {core_name} carries {hetero_pattern}.",
    "hetero_multi": "{hetero_clauses}.",
    "no_hetero": "The ring system is an all-carbon framework.",
    # Aromaticity and saturation.
    "aromaticity": "Overall the framework is {aromaticity_desc}.",
    # Attachment positions.
    "attachment": "Open substitution {is_are} found at {attachment_desc}.",
}


MAX_SENTENCES_TEXT = "four"



# -------------------------------------------------------------------------- #
#  Faithfulness rules: never go beyond FACTS. v1's exhaustive-coverage
#  requirement was intentionally removed.
# -------------------------------------------------------------------------- #
_FAITHFULNESS_RULES = """\
  - The FACTS describe a Bemis-Murcko SCAFFOLD (ring systems plus the linkers joining them, all
    substituents stripped). Describe that scaffold, not a whole drug molecule, and never imply the
    stripped substituents are known.
  - Whatever you do state must match the FACTS exactly: ring and heterocycle names, ring sizes,
    aromatic-vs-saturated state, heteroatom counts, and how the ring systems are joined (fused /
    spiro / bridged / biaryl / a named linker). Never rename, swap, or approximate one of these.
  - Introduce no ring, heterocycle, or heteroatom that the FACTS do not list, and give no total or
    count the FACTS do not give.
  - Match aromaticity exactly: an aromatic ring stays aromatic; a saturated ring is not aromatic
    and must never be called aromatic or aryl.
  - If you mention a linker, keep its identity and its chain shape as the FACTS give them,
    including any double-bonded oxygen or sulfur - a thiourea keeps its C=S, an amide, urea, ester
    or carbamate keeps its C=O, a sulfonamide keeps its S(=O)2. Never flatten one into a plain
    saturated chain.
  - If you mention a ring that the FACTS say bears a lactam, lactone, cyclic urea, cyclic imide or
    ring ketone, keep that carbonyl - do not reduce the ring to its plain parent heterocycle.
  - POSITIONS: you may state a ring locant or a linker attachment point ONLY when the FACTS give it
    verbatim. Invent no other position. Substituent positions are never in the FACTS (substituents
    are stripped), so never say where a substituent attaches, never call a position "open" or
    "available", and never give a benzene's ortho/meta/para pattern.
  - The scaffold is NEUTRAL: never say protonated, charged, cation, or anion. Do not assign
    stereochemistry (no chiral, (R)/(S), stereocenter) - this is ring topology, not configuration.
  - Invent no biological activity, potency, target, binding pocket, or "privileged scaffold" claim,
    and add no purpose tail (never say the scaffold is for SAR, or for further substitution,
    elaboration or functionalization, or what could later be attached).
  - The scaffold SMILES in the FACTS is reference only: do not re-derive chemistry from it, do not
    quote it, and do not mention SMILES, SMARTS, patterns, or queries at all."""


# -------------------------------------------------------------------------- #
#  Uniform voice: target only model-to-model differences observed in outputs.
# -------------------------------------------------------------------------- #
_UNIFORM_VOICE = """\
  - NAMING: call every ring exactly what the FACTS call it. If the FACTS say "benzene", write
    benzene - not phenyl, not aryl, not "a six-membered aromatic carbocycle". Same for every other
    ring name. Do not substitute a synonym, an adjectival form, or a systematic paraphrase.
  - PLAIN WORDS: use ordinary connecting verbs - linked, joined, attached, connected, carries,
    bears, fused. Avoid ornamental ones (tethered, flanked, welded, decorated, anchored, appended,
    hosts, showcases) and avoid the filler nouns "framework", "moiety", "ring system(s)",
    "architecture", "entity".
  - PLAIN TYPOGRAPHY: ASCII only. Use the ordinary hyphen-minus "-" in chemical names and linker
    patterns; never a non-breaking hyphen, en dash or em dash. Write S(=O)2 and CH2 with ordinary
    digits; never subscript characters. Use straight quotes.
  - PLAIN REGISTER: flat declarative statements. No rhetorical build-up, no "notably", no
    "interestingly", and no closing sentence that merely restates what you already said."""


# -------------------------------------------------------------------------- #
#  SYSTEM_PROMPT
# -------------------------------------------------------------------------- #
SYSTEM_PROMPT = """\
You are an experienced medicinal chemist describing a molecular SCAFFOLD (a ring framework with \
all substituents stripped off) in natural, everyday chemical English.

For each scaffold you get two things:
  (1) SCAFFOLD FACTS - deterministic, computed from the molecule by RDKit. This is the ground \
truth and the OUTER LIMIT of what you may say.
  (2) DRAFT - a stiff template rendering of some of those facts. Rewrite it; do not copy it.

REGISTER - read this first:
  You are writing the brief a chemist states when asking for a structure to be made. It is read
  before any structure exists, and more than one structure can satisfy it, so do not OPEN by
  pointing at a finished object. Never begin with "This scaffold ...", "The scaffold ...", "The
  structure ...", "This framework ...". Start from a part - a named ring, a linker, the
  heteroatoms - and say how the pieces go together, the way a chemist sketches a target out loud:
    "A quinazoline core linked through an amide to a pyridine ring, ..."
    not "This scaffold contains a quinazoline core ..."
  Never mention SMILES, SMARTS, patterns or queries anywhere in the text.
  If you do need to refer back to the whole thing later on, the word is "the scaffold" - not "the
  framework", "the system", "the structure" or "the architecture".

NO CLOSING SUMMARY - this is where descriptions usually go wrong:
  Every sentence must add structural information that no earlier sentence already gave. Never end
  with a sentence that totals up or restates what you have already said. For example:
    "A benzene ring is directly bonded to a saturated cyclopropane ring. The cyclopropane
     connects to a second benzene ring through a four-atom linker with a -C(=O)-O-N=CH- chain
     shape, combining ester and oxime ether features. The scaffold contains two aromatic rings
     and one saturated ring."
  The third sentence adds nothing - both benzenes and the cyclopropane were already named and
  their aromaticity was already implied. Delete it and stop at the second sentence.
  NO EMPTY PREDICATE. Never add a verb phrase whose only job is to give the sentence something
  to do: "forms the core of the scaffold", "forms the entire scaffold", "serves as the central
  hub", "constitutes the framework", "makes up the structure". If one ring is all there is, say
  it as a plain noun phrase and stop - "A single aromatic benzene ring, six-membered and
  all-carbon." A one-phrase answer is a complete brief; padding it into a sentence adds nothing.
  Heteroatom totals ("three nitrogens in all") and overall aromatic-vs-saturated tallies are
  exactly this kind of recap once the rings have been named individually. Leave them out. Stop as
  soon as the parts and their connections have been stated.

WHAT TO SAY:
  - Your goal is ONE natural, readable description - the way a chemist would actually describe \
this scaffold out loud. Naturalness comes first.
  - You do NOT have to mention every fact. Select what matters and let the rest go. A short, clean \
sentence beats an exhaustive one.
  - But say NOTHING the FACTS do not give. Everything you write must be traceable to them. \
Omitting is fine; adding is not.
  - Whatever you leave in must be UNAMBIGUOUS. Never write a vague back-reference like "this ring \
system", "the other ring", or "the heterocycle" when the scaffold has more than one candidate - \
name the ring instead. A reader who cannot tell which ring you mean is a failure, even if every \
word is technically true.
  - The DRAFT is your starting point for wording only. It is stiff, sometimes ambiguous, and \
sometimes incomplete. Rewrite it into fluent prose; do not mirror its sentence order or its \
opening.

RULES:
""" + _FAITHFULNESS_RULES + """

UNIFORM VOICE (these descriptions are TRAINING DATA produced by several different models; they \
must read as though one person wrote all of them):
""" + _UNIFORM_VOICE + """

FORM:
  - OPENING: begin with whatever is most characteristic here - the main named ring, the way the
    rings are joined, a fused/spiro/bridged motif, or the heteroatom pattern. Let the structure
    decide what comes first; no particular frame is required.
  - Length: at most """ + MAX_SENTENCES_TEXT + """ sentences, and roughly 30-60 words in total.
  - Output ONLY the description as flowing prose - no reasoning, no thinking, no step-by-step, no
    restating these rules, no markdown headers or lists, no preamble ("Here is...", "The
    description:"). Begin directly with the description."""


# -------------------------------------------------------------------------- #
#  USER_TEMPLATE
# -------------------------------------------------------------------------- #
USER_TEMPLATE = """\
SCAFFOLD FACTS (authoritative - the outer limit of what you may say; you need not use all of it):
{facts}

DRAFT (a stiff template rendering, REFERENCE ONLY - rewrite it, do not follow its wording, \
sentence order, or opening):
{draft}

Write one natural description of this scaffold: at most """ + MAX_SENTENCES_TEXT + """ sentences, \
roughly 30-60 words, naming the parts directly (never "this scaffold" / "the \
scaffold" / "the molecule"), saying nothing the FACTS do not give, and leaving no ring \
ambiguous. Output only the description."""


# -------------------------------------------------------------------------- #
#  REVISE_TEMPLATE
# -------------------------------------------------------------------------- #
REVISE_TEMPLATE = """\
SCAFFOLD FACTS (authoritative - the outer limit of what may be said):
{facts}

A DRAFT description was written, but a deterministic check found the following ISSUE(S) - each is \
either a FACTUAL ERROR contradicting the SCAFFOLD FACTS or a STYLE-RULE violation. Every one MUST \
be fixed:
{violations}

DRAFT (to be corrected):
{draft}

Rewrite so EVERY listed issue is fixed, keeping everything already correct and the same overall \
style and length (at most """ + MAX_SENTENCES_TEXT + """ sentences). Say nothing the SCAFFOLD \
FACTS do not give. Output ONLY the corrected description as one paragraph - no preamble, no list, \
no markdown, and do not mention the issues."""


# -------------------------------------------------------------------------- #
#  CONDENSE_TEMPLATE
# -------------------------------------------------------------------------- #
CONDENSE_TEMPLATE = """\
Rewrite the following scaffold description in AT MOST {max_sentences} sentence(s). Keep it natural \
and unambiguous, drop the least important details rather than compressing everything, and add \
nothing new. Output only the rewritten text, no preamble or markdown:

{text}"""
